version: '3.7'
services:
  api:
    container_name: SE1-Shop-api
    depends_on:
      - db
    tty: true
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    expose:
      - '3001'
    ports:
      - '3001:3001'
  client:
    container_name: SE1-Shop-client
    tty: true
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
  db:
    container_name: SE1-Shop-db
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
#TODO: add restarts, change mongodb image, test!!
